name: stats-causal
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pandas
  - numpy
  - scipy
  - statsmodels
  - matplotlib
  - seaborn
  - jupyterlab
  - pip
  - pip:
      - linearmodels
      - causalinference
      - causaldata
      - dowhy
      - econml
      - kaggle
